export const countries = [
    { id: 1, sortCode: 'IT', name: 'Italy' },
    { id: 2, sortCode: 'DE', name: 'Germany' },
    { id: 3, sortCode: 'SI', name: 'Slovenia' },
    { id: 4, sortCode: 'NL', name: 'Netherlands' },
    { id: 5, sortCode: 'FR', name: 'France' },
    { id: 6, sortCode: 'BE', name: 'Belgium' },
    { id: 7, sortCode: 'ES', name: 'Spain' },
    { id: 8, sortCode: 'RO', name: 'Romania' },
    { id: 9, sortCode: 'CZ', name: 'Czech Republic' },
    { id: 10, sortCode: 'DK', name: 'Denmark' },
    { id: 11, sortCode: 'HU', name: 'Hungary' },
    { id: 12, sortCode: 'AT', name: 'Austria' },
    { id: 13, sortCode: 'SE', name: 'Sweden' },
    { id: 14, sortCode: 'RS', name: 'Serbia' },
    { id: 15, sortCode: 'CY', name: 'Cyprus' },
    { id: 16, sortCode: 'LU', name: 'Luxembourg' },
    { id: 17, sortCode: 'PT', name: 'Portugal' },
    { id: 18, sortCode: 'UK', name: 'United Kingdom' }
  ];