export const sectors = [
        { id: 1, name: 'Pharmaceutical products' },
        { id: 2, name: 'Computer, Electronic and Optical products' },
        { id: 3, name: 'Air and Spacecraft machinery' },
        { id: 4, name: 'Chemicals and Chemical products' },
        { id: 5, name: 'Weapons and Ammunition' },
        { id: 6, name: 'Electrical Equipment' },
        { id: 7, name: 'Machinery and Equipment n.e.c.' },
        { id: 8, name: 'Motor Vehicles, Trailers and Semi-trailers' },
        { id: 9, name: 'Transport Equipment' },
        { id: 10, name: 'Medical, Dental instruments and Supplies' },
        { id: 11, name: 'Recorded Media' },
        { id: 12, name: 'Coke and Refined Petroleum products' },
        { id: 13, name: 'Rubber and Plastic products' },
        { id: 14, name: 'Other Non-metallic Mineral products' },
        { id: 15, name: 'Basic Metals' },
        { id: 16, name: 'Fabricated Metal products' },
        { id: 17, name: 'Building of Ships and Boats' },
        { id: 18, name: 'Installation of Machinery' },
        { id: 19, name: 'Food products' },
        { id: 20, name: 'Beverages' },
        { id: 21, name: 'Tobacco products' },
        { id: 22, name: 'Textiles' },
        { id: 23, name: 'Wearing Apparel' },
        { id: 24, name: 'Leather and Related products' },
        { id: 25, name: 'Wood products' },
        { id: 26, name: 'Paper products' },
        { id: 27, name: 'Furniture' },
        { id: 28, name: 'Other manufacturing' }
];